name: test
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install changelog
        run: python3 -m pip install keepachangelog==2.0.0.dev5
      - name: Update changelog
        id: changelog
        run: |
          echo "new_version=$(python3 -m keepachangelog release)" >> "$GITHUB_OUTPUT"
          echo "Bumping version to ${{steps.changelog.outputs.new_version}}"      
          