name: test
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
  bump_version:
    # Only bump version on the merge of a pull request
    name: Bump version
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
        run: pip install keepachangelog==2.0.0.dev5
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Update changelog
        id: changelog
        run: |
          echo "new_version=$(python3 -m keepachangelog release)" >> "$GITHUB_OUTPUT"
          echo "Bumping version to ${{steps.changelog.outputs.new_version}}"      
          